### ISSUE TITLE
Probleme dans submit fiche localisation

### ISSUE THREAD

**Issue by l0wran917** [l0wran917/projet_web#19]
Quand on choisit un tuteur deja existant, on à une erreur de CIR
![capture d ecran de 2016-01-17 14 43 05](https://cloud.githubusercontent.com/assets/11029822/12377759/c34fd7fc-bd28-11e5-87e2-e2c55dbc7ba0.png)

**Comment by l0wran917** [comment]
Tromper de #issue lors du commit ... (Merci American Dad pour la distraction)
Done

**Comment by Neonebula** [comment]
Sa taffe bien à ce que je vois
Le 17 janv. 2016 15:16, "Bassin Laurent" <notifications@github.com> a
écrit :
