### ISSUE TITLE
Alignement des labels

### ISSUE THREAD

**Issue by Neonebula** [l0wran917/projet_web#20]
Sur la page du compte rendu de visite, pour un code qui differe d'une ligne il y a pas le même alignement, j'ai peux être des mauvais skills de bootstrap.
![screenshot_2](https://cloud.githubusercontent.com/assets/11029860/12377837/39d861c6-bd2b-11e5-83ad-ddf13e9139fd.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11029860/12377838/39e12536-bd2b-11e5-8d4c-9bf08afe4018.png)

**Comment by l0wran917** [comment]
Tromper du numero lors du commit (Cf. 19)
Je vois ça juste après pour ce probleme

**Comment by Neonebula** [comment]
What ?

**Comment by Neonebula** [comment]
Ah ok j'ai vu
